### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Red-Five** [Axway/docker-st#5]
Any advice welcome:
Attempting to build via Google Cloud Build as follows

export PROJECT_ID=redacted
export IMAGE_NAME=docker-st-server
git clone https://github.com/Axway/docker-st.git
cd docker-st/server
gcloud builds submit --tag gcr.io/${PROJECT_ID}/${IMAGE_NAME} .

Fails with error
Step 21/28 : RUN chmod +x $ST_HOME/docker/scripts/*.sh &&    chmod +x scripts/*.sh &&    unzip installkit.zip &&    rm -f installkit.zip &&    ./setup.sh -s /home/stuser/tmp/axway_installer.properties
 ---> Running in 2ae04537ab47
[91munzip:  cannot find or open installkit.zip, installkit.zip.zip or installkit.zip.ZIP.
The command '/bin/sh -c chmod +x $ST_HOME/docker/scripts/*.sh &&    chmod +x scripts/*.sh &&    unzip installkit.zip &&    rm -f installkit.zip &&    ./setup.sh -s /home/stuser/tmp/axway_installer.properties' returned a non-zero code: 9
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 9

**Comment by georgi-blagov** [comment]
Hello,

you must pass the ST installation zip for linux located in the context folder as argument during build - ... --build-arg INSTALL_KIT=zip-name ...
